export const DECISION_TYPES = Object.freeze({
  APPROVE_REFUND: 'APPROVE_REFUND',
  APPROVE_REPAIR: 'APPROVE_REPAIR',
  APPROVE_EXCHANGE: 'APPROVE_EXCHANGE',
  APPROVE_RECYCLE: 'APPROVE_RECYCLE',
  REJECT_REQUEST: 'REJECT_REQUEST',
  REQUEST_REINSPECTION: 'REQUEST_REINSPECTION',
});

export const DECISION_TYPE_VALUES = Object.values(DECISION_TYPES);
