export const FACILITY_TYPES = Object.freeze({
  WAREHOUSE: 'WAREHOUSE',
  REPAIR_CENTER: 'REPAIR_CENTER',
  RECYCLING_CENTER: 'RECYCLING_CENTER',
});

export const FACILITY_TYPE_VALUES = Object.values(FACILITY_TYPES);
