export const INSPECTION_STATUSES = Object.freeze({
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
});

export const INSPECTION_STATUS_VALUES = Object.values(INSPECTION_STATUSES);
