export const INSPECTION_CONDITIONS = Object.freeze({
  NEW: 'NEW',
  GOOD: 'GOOD',
  DAMAGED: 'DAMAGED',
  UNUSABLE: 'UNUSABLE',
  MISSING_PARTS: 'MISSING_PARTS',
});

export const INSPECTION_CONDITION_VALUES = Object.values(INSPECTION_CONDITIONS);

export const RECOMMENDED_OUTCOMES = Object.freeze({
  REFUND: 'REFUND',
  REPAIR: 'REPAIR',
  EXCHANGE: 'EXCHANGE',
  RECYCLE: 'RECYCLE',
  REJECT: 'REJECT',
});

export const RECOMMENDED_OUTCOME_VALUES = Object.values(RECOMMENDED_OUTCOMES);
