export const OWNER_TYPES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  COURIER: 'COURIER',
  FACILITY: 'FACILITY',
  RETAILER: 'RETAILER',
  REPAIR_CENTER: 'REPAIR_CENTER',
  RECYCLING_CENTER: 'RECYCLING_CENTER',
});

export const OWNER_TYPE_VALUES = Object.values(OWNER_TYPES);
