export const PICKUP_STATUSES = Object.freeze({
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  COLLECTED: 'COLLECTED',
  DELIVERED_TO_FACILITY: 'DELIVERED_TO_FACILITY',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

export const PICKUP_STATUS_VALUES = Object.values(PICKUP_STATUSES);
