export const TRANSFER_TYPES = Object.freeze({
  PICKUP: 'PICKUP',
  WAREHOUSE_HANDOFF: 'WAREHOUSE_HANDOFF',
  REPAIR_HANDOFF: 'REPAIR_HANDOFF',
  DISPOSAL: 'DISPOSAL',
});

export const TRANSFER_TYPE_VALUES = Object.values(TRANSFER_TYPES);
