import { CASE_STATUSES, CASE_STATUS_VALUES } from '../../constants/caseStatus.js';
import { ApiError } from '../../utils/ApiError.js';

const S = CASE_STATUSES;

export const allowedTransitions = Object.freeze({
  [S.CASE_CREATED]: [S.PICKUP_ASSIGNED, S.CANCELLED],
  [S.PICKUP_ASSIGNED]: [S.PICKUP_ACCEPTED, S.PICKUP_FAILED, S.CANCELLED],
  [S.PICKUP_ACCEPTED]: [S.ITEM_COLLECTED, S.PICKUP_FAILED, S.CANCELLED],
  [S.PICKUP_FAILED]: [S.PICKUP_ASSIGNED, S.CANCELLED],
  [S.ITEM_COLLECTED]: [S.IN_TRANSIT, S.DELIVERED_TO_FACILITY, S.FACILITY_RECEIVED],
  [S.IN_TRANSIT]: [S.DELIVERED_TO_FACILITY, S.FACILITY_RECEIVED],
  [S.DELIVERED_TO_FACILITY]: [S.FACILITY_RECEIVED],
  [S.FACILITY_RECEIVED]: [S.INSPECTION_ASSIGNED, S.INSPECTION_PENDING],
  [S.INSPECTION_ASSIGNED]: [S.INSPECTION_PENDING],
  [S.INSPECTION_PENDING]: [S.INSPECTION_COMPLETED, S.INSPECTION_REJECTED],
  [S.INSPECTION_COMPLETED]: [
    S.DECISION_PENDING,
    S.REFUND_REVIEW_PENDING,
    S.REPAIR_SCHEDULED,
    S.REPLACEMENT_RESERVED,
    S.RECYCLE_SCHEDULED,
  ],
  [S.DECISION_PENDING]: [
    S.REFUND_PENDING,
    S.REPAIR_PENDING,
    S.EXCHANGE_PENDING,
    S.RECYCLE_PENDING,
    S.REQUEST_REJECTED,
    S.REINSPECTION_REQUESTED,
  ],
  [S.REFUND_PENDING]: [S.REFUND_APPROVED],
  [S.REPAIR_PENDING]: [],
  [S.EXCHANGE_PENDING]: [],
  [S.RECYCLE_PENDING]: [],
  [S.REQUEST_REJECTED]: [],
  [S.REINSPECTION_REQUESTED]: [S.INSPECTION_ASSIGNED],
  [S.INSPECTION_REJECTED]: [S.CASE_COMPLETED],
  [S.REFUND_REVIEW_PENDING]: [S.REFUND_APPROVED, S.REFUND_REJECTED],
  [S.REFUND_APPROVED]: [S.REFUND_RECORDED],
  [S.REFUND_RECORDED]: [S.CASE_COMPLETED],
  [S.REFUND_REJECTED]: [S.CASE_COMPLETED],
  [S.REPAIR_SCHEDULED]: [S.IN_REPAIR, S.REPAIR_NOT_POSSIBLE],
  [S.IN_REPAIR]: [S.REPAIR_COMPLETED, S.REPAIR_NOT_POSSIBLE],
  [S.REPAIR_COMPLETED]: [S.RETURN_SHIPMENT_CREATED],
  [S.REPAIR_NOT_POSSIBLE]: [S.RETURN_SHIPMENT_CREATED, S.REFUND_REVIEW_PENDING],
  [S.RETURN_SHIPMENT_CREATED]: [S.RETURNED_TO_CUSTOMER],
  [S.RETURNED_TO_CUSTOMER]: [S.CASE_COMPLETED],
  [S.REPLACEMENT_RESERVED]: [S.REPLACEMENT_SHIPPED, S.REPLACEMENT_UNAVAILABLE],
  [S.REPLACEMENT_SHIPPED]: [S.EXCHANGE_COMPLETED],
  [S.EXCHANGE_COMPLETED]: [S.CASE_COMPLETED],
  [S.REPLACEMENT_UNAVAILABLE]: [S.REFUND_REVIEW_PENDING, S.CASE_COMPLETED],
  [S.RECYCLE_SCHEDULED]: [S.ITEM_RECYCLED],
  [S.ITEM_RECYCLED]: [S.CASE_COMPLETED],
  [S.CASE_COMPLETED]: [],
  [S.CANCELLED]: [],
});

export const canTransition = (fromStatus, toStatus) =>
  Boolean(allowedTransitions[fromStatus]?.includes(toStatus));

export const assertValidTransition = (fromStatus, toStatus) => {
  if (!CASE_STATUS_VALUES.includes(fromStatus) || !CASE_STATUS_VALUES.includes(toStatus)) {
    throw new ApiError(400, 'Unknown case status');
  }
  if (!canTransition(fromStatus, toStatus)) {
    throw new ApiError(409, `Invalid case status transition: ${fromStatus} -> ${toStatus}`);
  }
};
